matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-27
          - build-tools-27.0.3
      before_script:
        - cd youtube-android/inline-youtube-view
      script:
        - ./gradlew build connectedCheck

    - language: objective-c
      osx_image: xcode7.3
      before_script:
        - cd youtube-ios
      script:
        - gem install cocoapods # Since Travis is not always on latest version
        - pod install --project-directory=Example
        - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/InlineYoutubeView.xcworkspace -scheme InlineYoutubeView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
        - pod lib lint

notifications:
  email:
    - anirudh.r@flipkart.com
